# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'exportWindowV1.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import time


class Export_Dialog(QtWidgets.QDialog):
    def __init__(self, parent=None):
        super().__init__()
        self.setupUi(self)
        
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.container_layout = QtWidgets.QVBoxLayout()
        self.container_layout.setObjectName("container_layout")
        self.file_name_layout = QtWidgets.QVBoxLayout()
        self.file_name_layout.setObjectName("file_name_layout")
        self.file_name_label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.file_name_label.setFont(font)
        self.file_name_label.setObjectName("file_name_label")
        self.file_name_layout.addWidget(self.file_name_label)
        self.file_name_instructions = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.file_name_instructions.setFont(font)
        self.file_name_instructions.setObjectName("file_name_instructions")
        self.file_name_layout.addWidget(self.file_name_instructions)
        self.file_input_box = QtWidgets.QLineEdit(Dialog)
        self.file_input_box.setInputMask("")
        self.file_input_box.setObjectName("file_input_box")
        self.file_name_layout.addWidget(self.file_input_box)
        self.container_layout.addLayout(self.file_name_layout)
        self.output_layout = QtWidgets.QVBoxLayout()
        self.output_layout.setObjectName("output_layout")
        self.export_format_label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.export_format_label.setFont(font)
        self.export_format_label.setObjectName("export_format_label")
        self.output_layout.addWidget(self.export_format_label)
        self.format_selection_box = QtWidgets.QComboBox(Dialog)
        self.format_selection_box.setEditable(False)
        self.format_selection_box.setObjectName("format_selection_box")
        self.format_selection_box.addItem("")
        self.format_selection_box.addItem("")
        self.output_layout.addWidget(self.format_selection_box)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.output_layout.addWidget(self.buttonBox)
        self.container_layout.addLayout(self.output_layout)
        self.gridLayout.addLayout(self.container_layout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Export Settings"))
        self.file_name_label.setText(_translate("Dialog", "1. File Name"))
        self.file_name_instructions.setText(_translate("Dialog", "Input file name below without file extension"))
        self.file_input_box.setText(_translate("Dialog", "exampleFileName"))
        self.export_format_label.setText(_translate("Dialog", "2. Output Format"))
        self.format_selection_box.setCurrentText(_translate("Dialog", "PNG"))
        self.format_selection_box.setItemText(0, _translate("Dialog", "PNG"))
        self.format_selection_box.setItemText(1, _translate("Dialog", "CSV"))

class Writing_Dialog(QtWidgets.QDialog):
    def __init__(self, parent=None):
        super().__init__()
        self.setWindowFlags(QtCore.Qt.SubWindow)
        self.setupUi(self)
    
    def setupUi(self, Dialog):
        Dialog.setObjectName("WDialog")
        Dialog.resize(200, 200)
        Dialog.setWindowModality(False)
        Dialog.setWindowTitle("Working...")
        self.layout = QtWidgets.QVBoxLayout(Dialog)
        self.layout.setAlignment(QtCore.Qt.AlignCenter)
        self.label = QtWidgets.QLabel("This may take a while")
        font = self.label.font()
        font.setPointSize(18)
        font.setBold(True)
        self.label.setFont(font)
        self.layout.addWidget(self.label)
        self.load_label = QtWidgets.QLabel()
        self.load_label.setMinimumSize(200, 50)
        self.load_label.setAlignment(QtCore.Qt.AlignCenter)
        self.layout.addWidget(self.load_label)
        movie = QtGui.QMovie("./loader.gif")
        movie.setScaledSize(QtCore.QSize(200, 50))
        self.load_label.setMovie(movie)
        movie.start()
            
class Alert_Dialog(QtWidgets.QDialog):
    def __init__(self, parent=None):
        super().__init__()
        self.setWindowFlags(QtCore.Qt.SubWindow)
        self.setupUi(self)
        
    def setupUi(self, Dialog):
        Dialog.setObjectName("ADialog")
        Dialog.resize(250, 250)
        Dialog.setWindowModality(True)
        Dialog.setWindowTitle("Working...")
        self.layout = QtWidgets.QVBoxLayout(Dialog)
        self.layout.setAlignment(QtCore.Qt.AlignCenter)
        self.label = QtWidgets.QLabel("This may take a while")
        font = self.label.font()
        font.setPointSize(18)
        font.setBold(True)
        self.label.setFont(font)
        self.layout.addWidget(self.label)
        self.load_label = QtWidgets.QLabel()
        self.load_label.setMinimumSize(200, 50)
        self.load_label.setAlignment(QtCore.Qt.AlignCenter)
        self.layout.addWidget(self.load_label)
        movie = QtGui.QMovie("./loader.gif")
        movie.setScaledSize(QtCore.QSize(200, 50))
        self.load_label.setMovie(movie)
        movie.start()
